services:
  db:
    image: postgres:16.4
    ports:
      - "5435:5432"
    volumes:
      - weblog_db-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=weblog_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=aminkhm

  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rabbitmq

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    restart: always
    ports:
      - "5673:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  celery_worker:
    build: .
    container_name: celery_worker
    command: celery -A config worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - app
      - rabbitmq
    restart: always

volumes:
  weblog_db-data: